// renderer/page/Title.vue
<template>
    <common-hero
        :title="t('title.title')"
        :subtitle="t('title.subtitle')"
    ></common-hero>

    <section class="section">
        <common-form :loading="loading" @submit="submitHandler"></common-form>

        <div class="notification">
            <strong>{{ t("label") }}</strong>
            <ul>
                <li>{{ t("title_structure") }}</li>
                <li>{{ t("ogp_structure") }}</li>
            </ul>
        </div>

        <template v-if="titleStore.result">
            <div class="notification is-primary">{{ titleStore.url }}</div>

            <h3 class="title is-4">{{ t("basic") }}</h3>

            <table class="table is-bordered is-fullwidth">
                <tbody>
                    <tr>
                        <th>Title</th>
                        <td>{{ titleStore.result.title }}</td>
                    </tr>
                    <tr>
                        <th>Description</th>
                        <td>{{ titleStore.result.description }}</td>
                    </tr>
                    <tr>
                        <th>Keyword</th>
                        <td>{{ titleStore.result.keywords }}</td>
                    </tr>
                    <tr>
                        <th>Vieport</th>
                        <td>{{ titleStore.result.viewport }}</td>
                    </tr>
                </tbody>
            </table>

            <h3 class="title is-4">OGP</h3>
            <table class="table is-bordered is-fullwidth">
                <tbody>
                    <tr>
                        <th>og:title</th>
                        <td>{{ titleStore.result["og:title"] }}</td>
                    </tr>
                    <tr>
                        <th>og:type</th>
                        <td>{{ titleStore.result["og:type"] }}</td>
                    </tr>
                    <tr>
                        <th>og:url</th>
                        <td>{{ titleStore.result["og:url"] }}</td>
                    </tr>
                    <tr>
                        <th>og:description</th>
                        <td>{{ titleStore.result["og:description"] }}</td>
                    </tr>
                    <tr>
                        <th>og:site_name</th>
                        <td>{{ titleStore.result["og:site_name"] }}</td>
                    </tr>
                    <tr>
                        <th>og:image</th>
                        <td>
                            {{ titleStore.result["og:image"] }}

                            <template
                                v-if="titleStore.result['og:image_preview']"
                                ><common-image
                                    :src="titleStore.result['og:image_preview']"
                                    @click="modal_image = $event"
                                    :max-width="600"
                                    :max-height="400"
                                ></common-image
                            ></template>
                        </td>
                    </tr>
                </tbody>
            </table>

            <h3 class="title is-4">SNS</h3>
            <table class="table is-bordered is-fullwidth">
                <tbody>
                    <tr>
                        <th>fb:app_id</th>
                        <td>{{ titleStore.result["fb:app_id"] }}</td>
                    </tr>
                    <tr>
                        <th>twitter:card</th>
                        <td>{{ titleStore.result["twitter:card"] }}</td>
                    </tr>
                    <tr>
                        <th>twitter:site</th>
                        <td>{{ titleStore.result["twitter:site"] }}</td>
                    </tr>
                </tbody>
            </table>
        </template>
    </section>

    <common-modal
        :modal-image="modal_image"
        @close="modal_image = ''"
    ></common-modal>
</template>

<script lang="ts">
import { defineComponent, Ref, ref } from "vue";
import { useI18n } from "vue-i18n";

// Store
import { useStore as useForm, Store as FormStore } from "../store/form";
import { useStore as useTitle, Store as TitleStore } from "../store/title";

const useSubmitHandler = (
    formStore: FormStore,
    titleStore: TitleStore,
    loading: Ref<boolean>
) => {
    return async () => {
        titleStore.url = "";
        titleStore.result = null;

        loading.value = true;
        const result = await (window as any).title_request(formStore);
        loading.value = false;

        if (!result) {
            window.alert("Failed to get specified URL");
            return;
        }

        titleStore.url = formStore.url;
        titleStore.result = result;
    };
};

export default defineComponent({
    name: "PageTitle",

    setup() {
        const formStore = useForm();
        const titleStore = useTitle();

        const loading = ref<boolean>(false);
        const modal_image = ref<string>("");
        const submitHandler = useSubmitHandler(formStore, titleStore, loading);

        return {
            titleStore,
            loading,
            modal_image,
            submitHandler,
            ...useI18n({
                messages: {
                    en: {
                        label:
                            "Remarks when you prepare the title/meta informations",
                        title_structure:
                            'For the title, You should follow the director\'s instruction. If there is no instruction, please input as "[Page name]｜[Site name]"',
                        ogp_structure:
                            "Unless otherwise specified, You should input og:title same with title and og:description same with description.",
                        basic: "Basic",
                    },
                    ja: {
                        label: "タイトル/メタタグ設定時の注意点",
                        title_structure:
                            "タイトルは原則ディレクター時指示に従ってください。指示がない場合は「ページ名｜サイト名」と指定してください",
                        ogp_structure:
                            "特に指定がない限り、og:titleはtitleと、og:descriptionにはdescriptionと同じ値を指定してください",
                        basic: "基本情報",
                    },
                },
            }),
        };
    },
});
</script>

// src/Pages/Title.tsx
import React, { useCallback, useState } from "react";
import {invoke} from '@tauri-apps/api/tauri'

// Components
import Typography from "@mui/material/Typography";
import Stack from "@mui/material/Stack";
import Box from "@mui/material/Box";
import Alert from "@mui/material/Alert";
import AlertTitle from "@mui/material/AlertTitle";
import CommonForm from '../Components/CommonForm';
import PageHeader from '../Components/PageHeader';
import Image from '../Components/Image';

const Dashboard: React.FunctionComponent = () => {
    const [result, setResult] = useState<Record<string, string> | null>(null);

    const handleSubmit = async (url: string, user: string, pass: string) => {
        const result = await invoke<Record<string, string>>('get_title_meta', {url, user, pass})
            .catch(e => alert(e))

        if (!result) {
            return false;
        }

        setResult(result);
        return true;
    }

    return <>
        <Stack gap={5}>
            <Stack gap={2}>
                <Box>
                    <PageHeader>Check Title/Meta</PageHeader>
                    <Typography>Checking Title and Meta informations</Typography>
                </Box>

                <CommonForm onSubmit={handleSubmit} />

                <Alert severity="info">
                    <AlertTitle>Remarks when you prepare the title/meta informations</AlertTitle>
                    For the title, You should follow the director's instruction. If there is no instruction, please input as "[Page name]｜[Site name]"<br />
                    Unless otherwise specified, You should input og:title same with title and og:description same with description.
                </Alert>
            </Stack>

            {result && (
                <>
                    <Stack gap={2}>
                        <Typography component="h3" variant="h6">Basic</Typography>

                        <Box>
                            <Typography fontWeight="bold" sx={{mb: 1}}>Title</Typography>
                            <Alert severity={result.title ? 'success' : 'error'}>
                                {result.title ?? 'Not found'}
                            </Alert>
                        </Box>

                        <Box>
                            <Typography fontWeight="bold" sx={{mb: 1}}>Description</Typography>
                            <Alert severity={result.description ? 'success' : 'error'}>
                                {result.description ?? 'Not found'}
                            </Alert>
                        </Box>

                        <Box>
                            <Typography fontWeight="bold" sx={{mb: 1}}>Keyword</Typography>
                            <Alert severity={result.keywords ? 'success' : 'error'}>
                                {result.keywords ?? 'Not found'}
                            </Alert>
                        </Box>

                        <Box>
                            <Typography fontWeight="bold" sx={{mb: 1}}>Vieport</Typography>
                            <Alert severity={result.viewport ? 'success' : 'error'}>
                                {result.viewport ?? 'Not found'}
                            </Alert>
                        </Box>
                    </Stack>

                    <Stack gap={2}>
                        <Typography component="h3" variant="h6">OGP</Typography>

                        <Box>
                            <Typography fontWeight="bold" sx={{mb: 1}}>og:title</Typography>
                            <Alert severity={result["og:title"] ? 'success' : 'error'}>
                                {result["og:title"] ?? 'Not found'}
                            </Alert>
                        </Box>

                        <Box>
                            <Typography fontWeight="bold" sx={{mb: 1}}>og:type</Typography>
                            <Alert severity={result["og:type"] ? 'success' : 'error'}>
                                {result["og:type"] ?? 'Not found'}
                            </Alert>
                        </Box>

                        <Box>
                            <Typography fontWeight="bold" sx={{mb: 1}}>og:url</Typography>
                            <Alert severity={result["og:url"] ? 'success' : 'error'}>
                                {result["og:url"] ?? 'Not found'}
                            </Alert>
                        </Box>

                        <Box>
                            <Typography fontWeight="bold" sx={{mb: 1}}>og:description</Typography>
                            <Alert severity={result["og:description"] ? 'success' : 'error'}>
                                {result["og:description"] ?? 'Not found'}
                            </Alert>
                        </Box>

                        <Box>
                            <Typography fontWeight="bold" sx={{mb: 1}}>og:site_name</Typography>
                            <Alert severity={result["og:site_name"] ? 'success' : 'error'}>
                                {result["og:site_name"] ?? 'Not found'}
                            </Alert>
                        </Box>

                        <Box>
                            <Typography fontWeight="bold" sx={{mb: 1}}>og:image</Typography>
                            <Alert severity={result["og:image"] ? 'success' : 'error'}>
                                {result["og:image"] ?? 'Not found'}

                                {result["og:image"] && <Box sx={{mt: 1}}><Image image={result["og:image"]} style={{maxWidth: 300}} /></Box> }
                            </Alert>
                        </Box>
                    </Stack>

                    <Stack gap={2}>
                        <Typography component="h3" variant="h6">SNS</Typography>

                        <Box>
                            <Typography fontWeight="bold" sx={{mb: 1}}>fb:app_id</Typography>
                            <Alert severity={result["fb:app_id"] ? 'success' : 'error'}>
                                {result["fb:app_id"] ?? 'Not found'}
                            </Alert>
                        </Box>

                        <Box>
                            <Typography fontWeight="bold" sx={{mb: 1}}>twitter:card</Typography>
                            <Alert severity={result["twitter:card"] ? 'success' : 'error'}>
                                {result["twitter:card"] ?? 'Not found'}
                            </Alert>
                        </Box>

                        <Box>
                            <Typography fontWeight="bold" sx={{mb: 1}}>twitter:site</Typography>
                            <Alert severity={result["twitter:site"] ? 'success' : 'error'}>
                                {result["twitter:site"] ?? 'Not found'}
                            </Alert>
                        </Box>
                    </Stack>
                </>
            )}
        </Stack>
    </>
}

export default Dashboard;
