// src/Pages/Dashboard.tsx
import React from "react";
import { useNavigate } from "react-router-dom";

// Components
import Stack from "@mui/material/Stack";
import Box from "@mui/material/Box";
import Typography from "@mui/material/Typography";
import Grid from "@mui/material/Grid";
import Card from "@mui/material/Card";
import CardActionArea from "@mui/material/CardActionArea";
import CardContent from "@mui/material/CardContent";
import PageHeader from "../Components/PageHeader";

const Dashboard: React.FunctionComponent = () => {
    const navigate = useNavigate();

    const handleClick = (path: string) => () => {
        navigate(path);
    };

    return (
        <Stack gap={4}>
            <Box>
                <PageHeader>Dashboard</PageHeader>
                <Typography>Checker support tools</Typography>
            </Box>

            <Grid container spacing={2}>
                <Grid item xs={12} md={6}>
                    <Card>
                        <CardActionArea onClick={handleClick("/title/")}>
                            <CardContent>
                                <Typography
                                    gutterBottom
                                    variant="h6"
                                    component="div"
                                    fontWeight="bold">
                                    Check Title/Meta
                                </Typography>
                                <Typography
                                    variant="body2"
                                    color="text.secondary">
                                    Checking Title and Meta informations
                                </Typography>
                            </CardContent>
                        </CardActionArea>
                    </Card>
                </Grid>
                <Grid item xs={12} md={6}>
                    <Card>
                        <CardActionArea onClick={handleClick("/alt/")}>
                            <CardContent>
                                <Typography
                                    gutterBottom
                                    variant="h6"
                                    component="div"
                                    fontWeight="bold">
                                    Check Alt
                                </Typography>
                                <Typography
                                    variant="body2"
                                    color="text.secondary">
                                    Check Alt attribute function
                                </Typography>
                            </CardContent>
                        </CardActionArea>
                    </Card>
                </Grid>
                <Grid item xs={12} md={6}>
                    <Card>
                        <CardActionArea onClick={handleClick("/headline/")}>
                            <CardContent>
                                <Typography
                                    gutterBottom
                                    variant="h6"
                                    component="div"
                                    fontWeight="bold">
                                    Check Headline
                                </Typography>
                                <Typography
                                    variant="body2"
                                    color="text.secondary">
                                    Checking Headline structure
                                </Typography>
                            </CardContent>
                        </CardActionArea>
                    </Card>
                </Grid>
                <Grid item xs={12} md={6}>
                    <Card>
                        <CardActionArea onClick={handleClick("/link/")}>
                            <CardContent>
                                <Typography
                                    gutterBottom
                                    variant="h6"
                                    component="div"
                                    fontWeight="bold">
                                    Check Link
                                </Typography>
                                <Typography
                                    variant="body2"
                                    color="text.secondary">
                                    Check Link target available
                                </Typography>
                            </CardContent>
                        </CardActionArea>
                    </Card>
                </Grid>
            </Grid>
        </Stack>
    );
};

export default Dashboard;

// renderer/page/Dashboard.vue
<template>
    <common-hero
        title="Dashboard"
        subtitle="Checking support tools"
    ></common-hero>

    <section class="section">
        <div class="container">
            <div class="columns">
                <div class="column">
                    <router-link :to="{ name: 'title' }">
                        <div class="card">
                            <header class="card-header">
                                <p class="card-header-title">
                                    Check Title/Meta
                                </p>
                            </header>
                            <div class="card-content">
                                <div class="content">
                                    Checking Title and Meta informations
                                </div>
                            </div>
                        </div>
                    </router-link>
                </div>

                <div class="column">
                    <router-link :to="{ name: 'alt' }">
                        <div class="card">
                            <header class="card-header">
                                <p class="card-header-title">Check Alt</p>
                            </header>
                            <div class="card-content">
                                <div class="content">
                                    Checking Alt attribute is empty or not
                                </div>
                            </div>
                        </div>
                    </router-link>
                </div>

                <div class="column">
                    <router-link :to="{ name: 'headline' }">
                        <div class="card">
                            <header class="card-header">
                                <p class="card-header-title">Check Headline</p>
                            </header>
                            <div class="card-content">
                                <div class="content">
                                    Checking Headline structure
                                </div>
                            </div>
                        </div>
                    </router-link>
                </div>

                <div class="column">
                    <router-link :to="{ name: 'link' }">
                        <div class="card">
                            <header class="card-header">
                                <p class="card-header-title">Check Link</p>
                            </header>
                            <div class="card-content">
                                <div class="content">
                                    Check Link target function
                                </div>
                            </div>
                        </div>
                    </router-link>
                </div>
            </div>
        </div>
    </section>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
    name: "PageDashboard",
});
</script>
